name: Create Design Review Issue

on:
  schedule:
    # Every Wednesday at 00:00:00
    - cron: '0 0 * * 3'

jobs:
  create-design-review-issue:
    if: github.repository == 'ampproject/amphtml'
    name: Create Design Review Issue
    runs-on: ubuntu-latest
    steps:
      - name: Create Design Review Issue
        run: |
          wget -q -O - "https://raw.githubusercontent.com/ampproject/amphtml/main/.github/workflows/create-design-review-issue.js" | node
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
