name: Release tagger
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'tagger action (promote | rollback)'
        required: true
      head:
        description: 'head AMP version'
        required: true
      base:
        description: 'base AMP version'
        required: true
      channel:
        description: 'release channel (beta-opt-in | beta-percent | stable | lts)'
        required: true
      sha:
        description: 'commit sha'
        required: true
permissions:
  contents: read

jobs:
  tagger:
    environment: release_tagger
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: lts/*
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: bash ./.github/workflows/install_dependencies.sh
      - name: Run tagger
        run: |
          node ./build-system/release-tagger/index.js \
            --action ${{ github.event.inputs.action }} \
            --head ${{ github.event.inputs.head }} \
            --base ${{ github.event.inputs.base }} \
            --channel ${{ github.event.inputs.channel }} \
            --sha ${{ github.event.inputs.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.AMPPROJECTBOT }}

  create-issue-on-error:
    if: failure()
    needs: tagger
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    environment: create_issue_on_error
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Create issue on error
        uses: JasonEtco/create-an-issue@e27dddc79c92bc6e4562f268fffa5ed752639abd # v2.9.1
        with:
          filename: .github/create_issue_on_error.md
        env:
          GITHUB_TOKEN: ${{ secrets.AMPPROJECTBOT }}
          WORKFLOW_NAME: ${{ github.workflow }}
          MENTION: '@ampproject/wg-infra'
          REPO_SLUG: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
