name: Request Validator Rollup

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'validator/**'
      - 'extensions/**/validator-*.*'

permissions:
  issues: write

jobs:
  rollup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2.9.2
        with:
          filename: .github/create_validator_rollup_issue.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MENTION: '@ampproject/wg-caching'
